### PR TITLE
fix navbar title on mobile & tablet

### PR DESCRIPTION
**Pull request by Arhell**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | yes

### Description

all in issue https://github.com/laminas/laminas.github.io/issues/92

### CODE REVIEW

**Comment by froschdesign** [comment]
@Arhell 
Your commit contains unrelated changes from a previous commit. Can you recheck it? Thanks!

**Comment by Arhell** [comment]
@froschdesign done

**Comment by froschdesign** [comment]
Now run the Gulp task "css" and add the rendered CSS file via commit to this pull request.

**Comment by Arhell** [comment]
Done, but there is a question, I have an empty script generated and font should not be included in the commit, right?

**Comment by froschdesign** [comment]
> I have an empty script generated and font should not be included in the commit

What do mean with empty script?

**Comment by Arhell** [comment]
I looked, this is due to the fact that after the installation, I pulled more fresh versions of the dependency
I think everything is fine

**Review by michalbundyra — APPROVED** [review]

**Comment by michalbundyra** [comment]
Thanks, @Arhell!

**Pull request merged**
