### PR TITLE
Set min-height for navbar so it is not very low on Safari

### LINKED ISSUE #17: Header issue on docs.laminas.dev on Safari
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | master

#### Summary

Header has invalid height on Safari:

image

The problem is present only on docs.laminas.dev.

### PR DESCRIPTION
**Pull request by michalbundyra**
|    Q          |   A
|-------------- | ------
| Bugfix        | yes

### Description

Fixes #17

### CODE REVIEW

**Comment by michalbundyra** [comment]
@froschdesign It requires building assets.

**Comment by michalbundyra** [comment]
@froschdesign You are correct. I forgot about mobile version.
Btw I've checked it and there is much more things we need to improve.

What about using media-queries to handle it properly for mobiles?

> The problem is only present on the overview of doc.laminas.dev therefore the priority of this issue quite small.

Yes, only on the overview, but - as this is the entry point for the whole documentation I would treat it with a bit higher priority :)

**Comment by froschdesign** [comment]
@michalbundyra 
Another idea:

```css
.navbar {
    flex-shrink: 0;
}
```
https://developer.mozilla.org/en-US/docs/Web/CSS/flex-shrink

**Comment by michalbundyra** [comment]
@froschdesign we can try this and then test on some devices we have available :)

**Comment by froschdesign** [comment]
Looks good on my Safari (Desktop).

**Comment by michalbundyra** [comment]
@froschdesign Would you be able to submit another PR, so this can be closed, please?

**Comment by froschdesign** [comment]
Sure. (This will also include all last changes in the rendered CSS file.)

**Comment by weierophinney** [comment]
Closed in favor of #34

**Pull request closed without merging**
