### PR TITLE
add new favicons

### PR DESCRIPTION
**Pull request by Arhell**
|    Q          |   A
|-------------- | ------
| New Feature   | yes

### Description

issue https://github.com/laminas/laminas.github.io/issues/102
add new favicons

### CODE REVIEW

**Review by froschdesign — CHANGES_REQUESTED** [review]
The current version of the logo does not work well. Example:

Bildschirmfoto 2020-09-02 um 20 43 11

We should use the version with a background. (The same applies to the other subprojects.)

**Comment by froschdesign** [comment]
I will upload all trademark logos to a central place and then we can use them.

**Comment by Arhell** [comment]
@froschdesign updated icons

**Comment by froschdesign** [comment]
We should remove all images from this repository and use the [repository for the getlaminas.org website](https://github.com/laminas/getlaminas.org) as central place for all images, logos, icons and so on. Otherwise we duplicate the files in different repositories.

This means for the favorite icons that only the HTML must be updated in this repository – when all icons are available.

---

I added all missing trademark logos to getlaminas.org repository: https://github.com/laminas/getlaminas.org/pull/60
I will also update the documentation theme [to output the correct logo](https://github.com/laminas/documentation-theme/blob/efdd033f9f16b93dd7489012db3036720c930ffa/theme/main.html#L15) of the subproject in the related documentations.

**Comment by Arhell** [comment]
> We should remove all images from this repository and use the [repository for the getlaminas.org website](https://github.com/laminas/getlaminas.org) as central place for all images, logos, icons and so on. Otherwise we duplicate the files in different repositories.
> 
> This means for the favorite icons that only the HTML must be updated in this repository – when all icons are available.
> 
> I added all missing trademark logos to getlaminas.org repository: [laminas/getlaminas.org#60](https://github.com/laminas/getlaminas.org/pull/60)
> I will also update the documentation theme [to output the correct logo](https://github.com/laminas/documentation-theme/blob/efdd033f9f16b93dd7489012db3036720c930ffa/theme/main.html#L15) of the subproject in the related documentations.

Great, just site.webmanifest (json)
i will need to add the repository for this, because transferring data from another place is impossible due to security

**Pull request closed without merging**
