### PR TITLE
make table of contents sticky (fixes #60)

### LINKED ISSUE #60: Very long table of contents overlaps footer section
#### Summary

On pages with a lot of content and many headlines, the table of contents is very long and overlaps the footer section.

#### How to reproduce

Problem is present on following pages:

* https://docs.laminas.dev/laminas-filter/standard-filters/#whitelist
* https://docs.laminas.dev/laminas-mvc/migration/to-v3-0/#laminasmvcviewsendresponselistener
* https://docs.laminas.dev/laminas-cache/storage/adapter/
* …

#### Expected behavior

The entire table of contents must be usable and may not overlap any other page section.

### PR DESCRIPTION
**Pull request by driehle**
|    Q          |   A
|-------------- | ------
| Bugfix        | yes

### Description

Fixes #60 by applying `position: sticky;` to the table of contents instead of `position: fixed;`.

Should work for all major browsers, see https://caniuse.com/?search=position%3Asticky.

### CODE REVIEW

**Comment by weierophinney** [comment]
@driehle Did you get a chance to build and try it? I'd like to see a quick screencast or animation that shows it in action before I merge, unless @froschdesign can sign off on it.

**Comment by froschdesign** [comment]
@weierophinney 
Don't worry, I'll take care of that.

**Comment by driehle** [comment]
I have still found a glitch, hence the update. This is how it looks now:

grafik

grafik

grafik

As you can see, its still not perfect, but much better than the current state, where you cannot make it past "projects":

grafik

For a better solution we would have to change the HTML structure, i.e. we would have to place `<div class="toc">` outside of `<main>`. However, I am not aware what changes that might need, since this will likely enforce changes for all component docs as well?

I can provide an updated PR including the HTML change if you like though.

**Comment by froschdesign** [comment]
@driehle 
Unfortunately your solution changes the position and removes the border of the table of contents. Compare with the following screenshots of the original layout:

Bildschirmfoto 2021-01-07 um 09 11 08
Bildschirmfoto 2021-01-07 um 09 14 57


> For a better solution we would have to change the HTML structure, i.e. we would have to place `<div class="toc">` outside of `<main>`.

Please make a suggestion for this.

**Comment by froschdesign** [comment]
@driehle 
Have you found a solution or another suggestion?

**Comment by driehle** [comment]
Closing in favour of #132

**Pull request closed without merging**
