### PR TITLE
fix component subtitle color on mobile

### PR DESCRIPTION
**Pull request by Arhell**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | yes

### Description
fix subtitle solor
https://github.com/laminas/laminas.github.io/issues/106

### CODE REVIEW

**Review by michalbundyra — APPROVED** [review]

**Comment by michalbundyra** [comment]
Thanks, @Arhell!

**Comment by froschdesign** [comment]
Please keep in mind: there are two component selectors!

The headline "Find documentation…" in the sidebar is not readable now.

**Comment by michalbundyra** [comment]
@froschdesign open separate issue for that, this is already merged/closed, thanks 👍

**Comment by froschdesign** [comment]
@michalbundyra 
Already done!

**Pull request merged**
